name: Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      
      - name: Instalar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Instalar las dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar test
        run: pytest

      # SOLO SI LOS TESTS PASAN, SE EJECUTAN ESTOS PASOS
      - name: Iniciar sesión en Docker Hub
        if: success()
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir la imagen Docker
        if: success()
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-api-fastapi:latest .

      - name: Subir la imagen a Docker Hub
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-api-fastapi:latest 
